name: alsan_app

description: Speech Therapy Platform

version: 0.1.20+20

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  amazon_payfort: ^1.1.1
  agora_chat_sdk: ^1.2.0
  agora_rtc_engine: ^6.3.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  csc_picker: ^0.2.7
  dio: ^5.5.0+1
  dotted_line: ^3.2.2
  dotted_decoration: ^2.0.0
  expandable_page_view: ^1.0.17
  file_picker: ^8.0.6
  firebase_analytics: ^10.1.1
  firebase_core: ^2.8.0
  flutter_downloader: ^1.11.8
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  flutter_date_pickers: ^0.4.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^9.9.1
  flutter_portal: ^1.1.4
  flutter_rating_bar: ^4.0.1
  fluro: ^2.0.5
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  intl_phone_number_input: ^0.7.4
  image_picker: ^1.1.2
  lottie: ^2.1.0
  map_launcher: ^3.3.1
  moment_dart: ^2.2.1+beta.0
  network_info_plus: ^6.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^22.1.34
  timelines: ^0.1.0
  uuid: ^3.0.5
  webview_flutter: ^4.8.0
  youtube_player_flutter: ^9.0.1

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/notify/
    - assets/icons/mode/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/readex_pro/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/readex_pro/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/readex_pro/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/readex_pro/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/readex_pro/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/readex_pro/ReadexPro-ExtraLight.ttf
          weight: 200

