name: alsan_app

description: Speech Therapy Platform

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_decoration: ^2.0.0
  fluro: ^2.0.4
  flutter_date_pickers: ^0.4.0
  flutter_portal: ^1.1.3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.1
  lottie: ^2.1.0
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_pdfviewer: ^20.2.41
  rxdart: ^0.27.7
  path_provider: ^2.0.11
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/readex_pro/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/readex_pro/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/readex_pro/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/readex_pro/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/readex_pro/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/readex_pro/ReadexPro-ExtraLight.ttf
          weight: 200

