name: alsan_app

description: Speech Therapy Platform

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  fluro: ^2.0.4
  flutter_date_pickers: ^0.4.0
  flutter_portal: ^1.1.3
  intl: ^0.17.0
  lottie: ^2.1.0
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_pdfviewer: ^20.2.41
  rxdart: ^0.27.7
  path_provider: ^2.0.11
  webview_flutter: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

