name: alsan_app

description: Speech Therapy Platform

version: 0.1.31+31

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  amazon_payfort: ^1.1.4
  agora_chat_sdk: 1.2.0
  agora_rtc_engine: ^6.5.0
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  csc_picker: ^0.2.7
  dio: ^4.0.6
  dotted_line: ^3.2.3
  dotted_decoration: ^2.0.0
  expandable_page_view: ^1.0.17
  file_picker: ^8.1.4
  firebase_analytics: ^10.1.1
  firebase_core: ^2.4.0
  flutter_downloader: ^1.10.2
#  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  flutter_date_pickers: ^0.4.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^17.2.2
  flutter_portal: ^1.1.3
  flutter_rating_bar: ^4.0.1
  fluro: ^2.0.4
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  http: ^0.13.5
  intl: ^0.19.0
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop
  image_picker: ^0.8.5+3
  lottie: ^2.1.0
  map_launcher: ^3.5.0
  moment_dart: ^0.17.4
  network_info_plus: ^4.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  syncfusion_flutter_pdfviewer: ^27.2.5
  timelines: ^0.1.0
  uuid: ^4.1.0
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.1


dependency_overrides:
  http: ^0.13.4
  html: ^0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/notify/
    - assets/icons/mode/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/readex_pro/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/readex_pro/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/readex_pro/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/readex_pro/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/readex_pro/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/readex_pro/ReadexPro-ExtraLight.ttf
          weight: 200

