// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMwIA6Ru_rrs-vXkAOreb0zwR3zPbACNc',
    appId: '1:1022577936384:android:9be801d74bd2a9178330e5',
    messagingSenderId: '1022577936384',
    projectId: 'talaqah-clinic',
    databaseURL: 'https://talaqah-clinic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'talaqah-clinic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArW8YqsStzzDPDSg7p2lg5G2n3WFib4Ok',
    appId: '1:1022577936384:ios:342f852d0e12a65a8330e5',
    messagingSenderId: '1022577936384',
    projectId: 'talaqah-clinic',
    databaseURL: 'https://talaqah-clinic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'talaqah-clinic.appspot.com',
    iosClientId: '1022577936384-medvndk8hbq84lkfpji1gkcsr9pd5jb1.apps.googleusercontent.com',
    iosBundleId: 'com.talaqah.app',
  );
}
