# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
before_all do
    ENV["FASTLANE_USER"] = "talaqah.services@gmail.com"
    ENV["FASTLANE_PASSWORD"] = "Ga123456@"
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
      build_app(workspace: "Runner.xcworkspace", scheme: "Runner", output_directory: "fastlane/build", output_name: "Runner.ipa")
      upload_to_testflight(ipa: "fastlane/build/Runner.ipa")

  end
end
